#version: 2
#updates:
#  - package-ecosystem: 'npm'
#    directory: '/'
#    schedule:
#      interval: 'monthly'
#    assignees:
#      - 'author'
#    reviewers:
#      - 'author'
#    open-pull-requests-limit: 10
#    versioning-strategy: increase
